export const Proyectos = [
  {
    nombre: "Raices Ibericas",
    url: "https://raicesibericas.com/",
    año: "",
    tecnologia: ["Shopify"],
    pais: "Desconocido",
  },
  {
    nombre: "Raices Ibericas Mission (Game)",
    url: "http://mission.raicesibericas.com/",
    año: "",
    tecnologia: ["React"],
    pais: "Desconocido",
  },
  {
    nombre: "Peer Collective",
    url: "https://peercollective.com/",
    año: "",
    tecnologia: ["WordPress Webapp"],
    pais: "Desconocido",
  },
  {
    nombre: "Bodegas Norton",
    url: "https://shop.norton.com.ar/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "La Comunidad del Bienestar",
    url: "https://lacomunidaddelbienestar.com.ar/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "Furore Carra",
    url: "https://furorecarra.com/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "Kodak Store",
    url: "http://kodakstore.com.ar/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "Marefish ",
    url: "http://marefish.es/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "WooCommerce",
    url: "http://azul.arrancar.com.ar/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "WooCommerce",
    url: "https://cncestudio.com.ar/",
    año: "",
    tecnologia: ["WooCommerce"],
    pais: "Desconocido",
  },
  {
    nombre: "RN Group PR",
    url: "https://www.rngrouppr.com/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Puerto Rico",
  },
  {
    nombre: "Mosaic the Movement",
    url: "http://mosaicthemovement.com/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "USA",
  },
  {
    nombre: "Trize Legal",
    url: "http://www.trizelegal.es/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Espana",
  },
  {
    nombre: "Trize Inmo",
    url: "http://www.trizeinmo.es/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Espana",
  },
  {
    nombre: "Mauricio Ghioldi",
    url: "https://mauricioghioldi.com.ar/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Argentina",
  },

  {
    nombre: "Mas Talento",
    url: "http://mastalento.net/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Argentina",
  },
  {
    nombre: "Expatsrs",
    url: "https://expatsrs.com/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Espana",
  },
  {
    nombre: "Fj Communications",
    url: "https://www.fjcommunications.com/",
    año: "",
    tecnologia: ["HTML", "CSS", "Javascript"],
    pais: "Espana",
  },
  {
    nombre: "Ciudades Subterraneas",
    url: "https://ciudadessubterraneas.com/",
    año: "",
    tecnologia: ["Angular"],
    pais: "Argentina",
  },
  {
    nombre: "Landing Qualia Seguros",
    url: "https://contrata.qualiaseguros.com/landing/productos",
    año: "",
    tecnologia: ["HTML", "CSS", "Javascript"],
    pais: "Desconocido",
  },
  {
    nombre: "Luz Frers",
    url: " https://luzfrers.com/",
    año: "",
    tecnologia: ["WordPress"],
    pais: "Argentina",
  },
];
